import {Button, TextEdit, LineEdit, VerticalBox, HorizontalBox, ListView} from "std-widgets.slint";

import {Message} from "message.slint";

InnerBox := Rectangle {
    VerticalBox {
        top-bar := LineEdit {
            placeholder-text: "Not Connected";
        }

        middle := ListView {
            background: transparent;

            for data[i] in [
                { text: "Hallo Clemens!", left: true, sender: "Artur" },
                { text: "Hi Artur!", left: false },
                { text: "Wie geht es dir?", left: false, different-sender: true },
                { text: "Help me!", left: true, sender: "Artur" },
                { text: "Ok!", left: false },
                { text: "Ich komme gleich!", left: false, different-sender: true },
                { text: "Dude ich habe keine Zeit, denn mir fehlen diese Dinge:\n- Geld\n- Zeit\n- ein gf", left: true, sender: "Artur" },
                { text: "Wenn du meinst...", left: false },
                { text: "Not OK!", left: true, sender: "Artur" },
                { text: "Was zur Hölle jungs?", left: true, sender: "Tim" },
                { text: "Ihr seid ja echt blöd", left: true, sender: "Tim", different-sender: true },
                { text: "Halts maul!", left: true, sender: "Maggs", different-sender: false },
                { text: "Ich fick euch blad alla!", left: false, different-sender: false },
            ] : Message {
                text: data.text;
                left: data.left;
                sender: data.sender;
                time: "12pm";
                different-sender: !data.different-sender;

                x: data.left ? 0 : parent.viewport-width - self.preferred-width - self.padding;
            }
        }

        bottom := HorizontalBox {
            vertical-stretch: 0;

            TextEdit {
                min-height: 11pt + 10px;
                border-width: 0px;
                background: transparent;

                Rectangle { 
                    padding: 2px;
                    border-color:  grey;
                    border-radius: 10px;
                    border-width:  padding;
                    height: parent.height;
                    width:  parent.width + 8*padding;
                    x: -4*padding;
                }
            }

            VerticalBox {
                Button {
                    text: "Send";
                }
                Button { 
                    text: "Add File";
                }
            }
        }
    }
}

export MainWindow := Window {
    title: "Pog Bilder";

    preferred-height: 500px;
    preferred-width:  500px;

    default-font-family: "Noto Mono";
    default-font-size:   12pt;

    inner := InnerBox { width: 100%; height: 100%; }
}